### ISSUE TITLE
English translation elements

### ISSUE THREAD

**Issue by vatterspun** [henrypp/freeshooter#3]
![2017-02-20 14_47_39-settings](https://cloud.githubusercontent.com/assets/1289134/23141260/92be969e-f77b-11e6-8971-ebe579f46d80.png)

"Параметры" should be "Options" and ÎÊ should be "OK"

Note sure what to suggest for the Effects tab:

![2017-02-20 14_49_13-settings](https://cloud.githubusercontent.com/assets/1289134/23141312/cd5558c4-f77b-11e6-87e6-2de993a5c951.png)

**Comment by henrypp** [comment]
i think you need to convert .lng files into utf16-le encoding.
and effect tabs untranslated config is "Disable Aero Effect for captured window"

**Comment by Tidos2** [comment]
Reencoding the file in utf16-le fix only one part of the problem. Now the text is displayed correct from the lng file but the translation to english is also missing because the part is in russian.

Here the original part of the English.lng:
`SettingsEffectsTab = Effects
SettingsResizeGroup = Resize
SettingsUseResize = Use resize
SettingsResizeWidth = Width:
SettingsResizeHeight = Height:
SettingsDisableAeroOnWnd = Отключать Aero окна
SettingsDisableAeroOnWndText = Перед созданием скриншота в режиме "Выбранное окно", Aero выбранного окна отключится, затем вернётся в состояние в котором и было`

Besides, if i start the program with no config it loads russian language. Maybe its better to load the english config as a default? Also a suggestion from me is that you use utf-8 or something similar for the encoding of the lng files and not Windows-1251.

**Comment by henrypp** [comment]
It means: Disable Aero effect before taking screenshot (only for Active window mode).
Binaries updated, but as you know - project closed, and no other changes will be.

**Comment by vatterspun** [comment]
Could you post something to the homepage of both the Github page and your home page that the project is closed?

https://www.henrypp.org/product/freeshooter
https://github.com/henrypp/freeshooter

**Comment by henrypp** [comment]
Project is open(source? lets coding together,lol), but i do not do anything with it.

**Comment by vatterspun** [comment]
> Project is open(source? lets coding together,lol), but i do not do anything with it.

Oh okay, I see the SRC folder now, thanks.
